services:
  - type: web
    name: portfolio-via-streamlit
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /_stcore/health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: PHONE_NUMBER
        sync: false
      - key: CALL_ME_BOT_API_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
